variable "project" {}
variable "region" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "az_1" {}
variable "az_2" {}
variable "ami_id" {}
variable "instance_type" {}
variable "instance_count" {}
variable "assign_public_ip" {}
